### ISSUE TITLE
Cannot reattach resistor after severing connection

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#10]
Shima reported:

> Once I had an issue with attaching and detaching a resistor to the internal terminals of  CCK-BB in the "build" tab.  The dashed circle at the one end of resistor detached from the resistor, and resistor ended up having one functional detachable terminal, so it could not be attached to anything on one side. I have attached a screen capture of the incident. I had to delete that problematic resistor and add another one.
> ![image](https://cloud.githubusercontent.com/assets/8419308/18643520/bf0bcb78-7e62-11e6-9a55-9b0bf96ea8e5.png)

This sounds like a bug, but I haven't been able to reproduce it. I'll follow up with Shima for more details.

**Comment by arouinfar** [comment]
Shima reported that she's only encountered this bug once. She's going to try to reproduce the issue, and she'll let us know what happens.

**Comment by arouinfar** [comment]
Shima was unable to reproduce this behavior.

**Comment by arouinfar** [comment]
I failed again to reproduce this while testing. Given the lack of reproducibility and that deleting the problematic component resolves the situation, I'm not sure that there's anything that needs to be done here @samreid.

**Comment by samreid** [comment]
Sounds good, let's reopen if we see the problem again.
