### ISSUE TITLE
Background should be gray when paused

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#13]
See https://github.com/phetsims/circuit-construction-kit-common/issues/213

**Comment by samreid** [comment]
When running with ?showPlayPauseButton the background should be a different color (gray was suggested) to indicate the simulation is paused. If we go with gray, we will need to choose a shade that doesn't blend too much with the junction colors.

**Comment by samreid** [comment]
I went with the color literal 'gray' and it was dark enough not to conflict with the vertices.  @arouinfar does this seem OK?

![image](https://cloud.githubusercontent.com/assets/679486/20116126/4ece851c-a5b8-11e6-80f9-cc0c651670d3.png)

**Comment by arouinfar** [comment]
Seems okay to me @samreid!

**Comment by arouinfar** [comment]
👍

**Comment by arouinfar** [comment]
As reported in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/16#issuecomment-259337320, deleting a circuit component while in play mode will trigger the pause (as it should), but the background color remains blue.

**Comment by samreid** [comment]
Let's pursue the problematic behavior in #16, closing.
