### ISSUE TITLE
When switching modes and the simulation pauses, the "animation speed reduced" still shows.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#14]
See https://github.com/phetsims/circuit-construction-kit-common/issues/212

**Comment by samreid** [comment]
During today's meeting, @arouinfar switched from "build" to "investigate" while the "animation speed reduced message was showing. The simulation was running with ?showPlayPauseButton and when the mode changed the simulation paused. Then in "investigate" mode, the "animation speed reduced" message was still showing.

**Comment by samreid** [comment]
> During today's meeting, @arouinfar switched from "build" to "investigate" while the "animation speed reduced message was showing. The simulation was running with ?showPlayPauseButton and when the mode changed the simulation paused. Then in "investigate" mode, the "animation speed reduced" message was still showing.

Translation: using ?screens=2&showPlayPauseButton

1) Switch to "test"
2) make the animation speed reduced message appear
3) switch to "explore"

the "animation speed reduced" message still appears, but it shouldn't

**Comment by samreid** [comment]
There is a hysteresis in the display message, and after the model slows down, it takes several time steps for the message to catch up.  Is that what we are seeing here?  I am seeing that the message disappears after the model has been unpaused for several frames.  @arouinfar is that acceptable?

**Comment by samreid** [comment]
Ah, I see, it should automatically pause due to #16, which is broken at the moment.

**Comment by samreid** [comment]
Perhaps a simple solution would be to hide the message if the sim is paused.  There could still be a temporary hysteresis effect when unpaused, but the message would disappear when switching modes.

**Comment by samreid** [comment]
Fixed in the above commit, and clear the history so it won't show up incorrectly for several frames.

**Comment by arouinfar** [comment]
> Perhaps a simple solution would be to hide the message if the sim is paused. 

That sounds like a reasonable solution to me @samreid.

**Comment by arouinfar** [comment]
Looks good!
