### ISSUE TITLE
In ?showPlayPauseButton, when changing the circuit, it should automatically pause

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#16]
This feature looks like it was inadvertently dropped during recent refactoring.

**Comment by arouinfar** [comment]
While in play mode, I tried changing the circuit a few different ways -- increasing R, increasing V, cutting a node, deleting an element. They all trigger a pause, but after deleting an element the background color remains blue until one of the elements is clicked in the toolbox. All other methods of changing the circuit behave properly.

Likely related to #13, which I'll reopen.

**Comment by samreid** [comment]
I'm seeing the screen turn from blue to gray when a component is deleted, can you please provide more information about how to reproduce the problem?  Here's what I observed:

![delete](https://cloud.githubusercontent.com/assets/679486/20150212/e4166432-a671-11e6-9cd6-137d278e38f4.gif)

**Comment by arouinfar** [comment]
Try building a circuit first, then deleting one of the components @samreid.

**Comment by arouinfar** [comment]
Here's a screencast @samreid. 
![pause](https://cloud.githubusercontent.com/assets/8419308/20150623/07fb9898-a674-11e6-9cf2-a8c7a34335d5.gif)

**Comment by samreid** [comment]
Thanks @arouinfar, this is ready for verification after the above commits.

**Comment by arouinfar** [comment]
👍
