### ISSUE TITLE
RC Testing for 1.0.4-phetiorc.1

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#17]
I fixed many issues (labeled with `fixed-pending-testing`) and this simulation needs to be RC tested before given to Stanford.  I have personally tested all of the `fixed-pending-testing` features, but all of the issues will benefit independent verification.  Also, the simulation underwent a bit of turbulence a few weeks ago, and we should test through and make sure the standard features are stable.

@arouinfar can you please take a look?  If everything seems good, I'll publish a release version we can share to our collaborators on phet-io.colorado.edu.

**Comment by samreid** [comment]
I assigned issues to @arouinfar for testing.  I'll address testing #12 since it requires launching a playback wrapper which is still under development.

**Comment by arouinfar** [comment]
@samreid is this the correct testing link? 
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.4-phetiorc.1/circuit-construction-kit-black-box-study_en-phetio.html

It's not loading for me, even when using the VPN. The PhET-io logo appears briefly, but then the screen becomes black.

**Comment by samreid** [comment]
My apologies, I meant to link to this comment but I forgot:

https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/12#issuecomment-259275126

It shows that the simulation is published here.

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.4-phetiorc.1/wrappers/index/

It is a phet-io simulation so cannot be launched without a wrapper (or query parameters to indicate it needs no wrapper), so I'd use the "Events: colorized" wrapper to run the simulation.

**Comment by arouinfar** [comment]
Got it @samreid. Thanks! I'll be testing this evening.

**Comment by arouinfar** [comment]
@samreid I'm being asked for login credentials. Can you email them to me?

<img width="374" alt="screen shot 2016-11-08 at 6 33 58 pm" src="https://cloud.githubusercontent.com/assets/8419308/20124207/f3cf46b8-a5e1-11e6-84a1-48c297b56bb8.png">

**Comment by samreid** [comment]
I emailed @arouinfar.

**Comment by arouinfar** [comment]
I'm finished testing for tonight @samreid. I'll test more thoroughly tomorrow morning.

**Comment by arouinfar** [comment]
@samreid back to you. No new issues to report.
