### ISSUE TITLE
RC Testing for 1.0.4-rc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#19]
I published a new version here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.4-phetiorc.2/wrappers/index/

@arouinfar can you please test the open issues that are pending testing, and take it for a larger test drive to make sure nothing is disturbed?  If all seems well, we could publish a production version for Shima.

EDIT: Changed "give this to Shima." to "publish a production version for Shima."

**Comment by arouinfar** [comment]
It's looking good @samreid! I haven't found any new issues to report, so I think it's ready for you to publish a version for Shima.
