### ISSUE TITLE
Share version 1.0.4-phetio

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#20]
I published https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.0.4-phetio/wrappers/index/

@arouinfar can you please share this version to Shima?  Please include links that show them the data stream, turn on the ?showPlayPauseButton, etc.  Also, I'll add a link momentarily that records data to Metacog that you can include.

UPDATE: See, for example, https://github.com/phetsims/circuit-construction-kit-common/issues/209#issuecomment-256459994 for the previous email we sent them.

**Comment by samreid** [comment]
Here's a link that shows a login page:

https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.0.4-phetio/wrappers/login/login.html?wrapper=record&sim=circuit-construction-kit-black-box-study&metacog&publisher_id=29da48a1&application_id=1f6fc35021bb7d398308c73123802036&widget_id=record-circuit-construction-kit-black-box-study&validationRule=crossCheckID&validationPrefix=cck16

Students enter IDs of the form:
cck16001a
cck16002b
...
cck16026z
cck16027a
cck16028b
etc.

For a testing ID, use cck16999k

When they are ready to use that link with students, they may request that we take down password protection during the study.

**Comment by arouinfar** [comment]
A few questions @samreid 

* Do we need a separate link for a version without electrons? I don't recall this being a simple query parameter.
* To use query parameters, it looks like I need to login with the testing ID and <i>then</i> add the query parameter to the end of the URL. Is this correct?
* More of an observation than a question... when I add ?phet-io.log=lines or ?phet-io.console, the developer console shows `phetio stepSimulation` messages being generated at a rate of 60 Hz. I don't remember this happening previously.

**Comment by arouinfar** [comment]
@samreid is this what I should use to hide electrons?

&phet-io.expressions=%5B%5B%22circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D,%5B%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D%5D

It seems to work, but I want to double check, since I'm less familiar with phet-io.

**Comment by samreid** [comment]
> Do we need a separate link for a version without electrons? I don't recall this being a simple query parameter.

The query parameter you provided above looks correct.

> To use query parameters, it looks like I need to login with the testing ID and then add the query parameter to the end of the URL. Is this correct?

Query parameters should be passed from the login page through to the simulation.  I tested and this appears to be working.  If you find otherwise, please let me know.

> * More of an observation than a question... when I add ?phet-io.log=lines or ?phet-io.log=console, the developer console shows `phetio stepSimulation` messages being generated at a rate of ~60 Hz. I don't remember this happening previously.

In order to support recording and playback, the record wrapper automatically records "input events" such as mouse moves, mouse presses and stepSimulation events.  This can be disabled with &phet-io.emitInputEvents=false.

For the first part of their testing, use links for "Events: colorized" which launches the PhET-iO simulation without an iframe.

**Comment by arouinfar** [comment]
Thanks @samreid!

> Query parameters should be passed from the login page through to the simulation. I tested and this appears to be working. If you find otherwise, please let me know.

That seems to be working for me now. Last night, it didn't seem to work that way, but I could have had a typo in my query parameter.

> In order to support recording and playback, the record wrapper automatically records "input events" such as mouse moves, mouse presses and stepSimulation events. This can be disabled with &phet-io.emitInputEvents=false.

Thanks for the clarification!

**Comment by samreid** [comment]
Here is the username/password:

Username: stanford
Password: forces
