### ISSUE TITLE
February: Classroom use of CCK/CCK Blackbox 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-black-box-study#25]
Shima and Argenta are collaborating on a classroom use of CCK (basically first screen only) and CCK: Black Box, and have requested instrumented/recording links for use in February. 

With final fixes for Shima's version happening now, we should be pretty set up. With primary addition being to create ability of an instrumented version with screen 1 only.

**Comment by kathy-phet** [comment]
@samreid - Not assigning you right now, but pinging you here so its on your radar for after delivery of Shima's interview links.

**Comment by kathy-phet** [comment]
Well - we need to send an updated link with the brightness issue fixed.

**Comment by samreid** [comment]
Sounds good, thanks @kathy-phet.  I'll reassign to myself and put this issue on hold until https://github.com/phetsims/circuit-construction-kit-dc/issues/16 is addressed.

**Comment by samreid** [comment]
I published a new version with the fixed lightbulb brightness, closing.
