### ISSUE TITLE
Voltmeter cannot read across wire stubs

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#26]
Found during https://github.com/phetsims/tasks/issues/761.

In Build mode, the voltmeter cannot read across the wire stubs attached to the black box. 
<img width="300" alt="screen shot 2017-01-05 at 12 24 59 pm" src="https://cloud.githubusercontent.com/assets/8419308/21694397/41a1fa1a-d342-11e6-8361-f5bf0bd5f16f.png">

However, the voltmeter can read across the black box terminals, even when the solder joint is not visible (as described in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/21#issuecomment-270730658). 
<img width="300" alt="screen shot 2017-01-05 at 12 25 07 pm" src="https://cloud.githubusercontent.com/assets/8419308/21694396/41a23c64-d342-11e6-8318-115493d13fc0.png">  <img width="337" alt="screen shot 2017-01-05 at 12 27 27 pm" src="https://cloud.githubusercontent.com/assets/8419308/21694457/9f8a6ce8-d342-11e6-8c4e-dafc968275b0.png">

This is somewhat problematic. Students may first probe the black box to see which terminals are connected to one another. If they do not place the probes directly on the black box terminals, they will get a ? reading, which corresponds to no connection.

**Comment by samreid** [comment]
Should we fix this and publish 1.0.6 for Shima?  This page https://github.com/phetsims/tasks/issues/761 says the next study is Jan 9 (Monday), should we try to fix it by then?

What is the desired behavior?  Making the wire stubs read the correct value, or making the black box vertex read as a "?"

**Comment by arouinfar** [comment]
@samreid the voltmeter probes should be able to read the correct value across the wire stubs and the black box vertices. It's currently only doing the latter.

If this is a quick and non-invasive change that won't require significant testing (which I doubt), please take care of it this afternoon. Otherwise, I can send 1.0.6 to Shima as-is, and let her know about this issue. She can decide if she wants to proceed with 1.0.4 or 1.0.6 for the pre-test she has planned for Monday.

We'll definitely need to fix this for the classroom study that's scheduled for February, however.

**Comment by samreid** [comment]
I added a new property `wireStub` and made it so it does not prevent wire voltages from being read from black box wires:

![image](https://cloud.githubusercontent.com/assets/679486/21730707/28371be2-d40e-11e6-81c5-4e85705f777b.png)

In testing this, I noticed that "Test" doesn't show the right voltages:
![image](https://cloud.githubusercontent.com/assets/679486/21730720/3b1e66f2-d40e-11e6-8240-a42803f267b4.png)

I'll need to check whether this was also a problem before.

**Comment by samreid** [comment]
Published to http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.7-phetio/circuit-construction-kit-black-box-study_en-phetio.html?phet-io.standalone=true

@arouinfar can you please take it for a test drive?

**Comment by arouinfar** [comment]
Thanks for the quick turnaround @samreid! I'll take a look now.

**Comment by arouinfar** [comment]
After some cursory testing, the voltmeter appears to work properly on the wire stubs. I'll have time to test this more deeply later this afternoon @samreid.

**Comment by samreid** [comment]
@arouinfar what is the status of this issue and what other issues do I need to fix before our next deployment?

**Comment by arouinfar** [comment]
@samreid I haven't found any issues with using the voltmeter across the wire stubs in 1.0.7, we we can go ahead and close this issue.
