### ISSUE TITLE
Voltmeter doesn't read values for black box circuit

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#27]
In testing this, I noticed that "Test" doesn't show the right voltages:
![image](https://cloud.githubusercontent.com/assets/679486/21730720/3b1e66f2-d40e-11e6-8240-a42803f267b4.png)

I'll need to check whether this was also a problem before.

From https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/26

@arouinfar have you seen this before?  Is this behavior correct for Black Box internals?  (Did we design it so the voltmeter cannot read from components inside the black box?)

**Comment by samreid** [comment]
This problem exists in 1.0.6 and 1.0.7.

**Comment by arouinfar** [comment]
I haven't seen this before @samreid, though I don't suppose I ever had the voltmeter probes arranged in such a way while testing.

Looks like voltmeter works if both probes are inside of the black box.
<img width="300" alt="screen shot 2017-01-06 at 1 03 21 pm" src="https://cloud.githubusercontent.com/assets/8419308/21731242/a960fcfe-d410-11e6-8814-1cb0ebcf4d68.png">  <img width="299" alt="screen shot 2017-01-06 at 1 03 42 pm" src="https://cloud.githubusercontent.com/assets/8419308/21731241/a960d490-d410-11e6-804a-14c4d3f18f10.png"> 

This is not the correct behavior. The only restriction is that the probes should not work if placed directly over the black box in Explore like so:
<img width="300" alt="screen shot 2017-01-06 at 1 15 26 pm" src="https://cloud.githubusercontent.com/assets/8419308/21731577/37de127c-d412-11e6-9037-55d5e4e1a274.png">

**Comment by arouinfar** [comment]
@samreid I've unassigned you from this issue until we hear back from Shima.  

The behavior of the voltmeter is not acceptable and will need to be addressed before delivering to Stanford. That said, I don't think you should spend any time on this issue until we have confirmation that the wire stubs don't require any other changes.

**Comment by arouinfar** [comment]
@samreid not sure how you'll be addressing this issue, given the change requests in #21, but here's the desired behavior for the current and voltmeters.
* Probes should produce a non-? reading across wires/vertices, including the Black Box wires/vertices.
* Probes should not be able to read on top of the black box, as shown in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/27#issuecomment-270995641
* Probes cannot read within the components themselves, like so
<img width=200 src="https://cloud.githubusercontent.com/assets/8419308/22035812/8c1a2142-dcae-11e6-9d8c-78e045e5b4a4.png">   <img width=200 src="https://cloud.githubusercontent.com/assets/8419308/22035884/bdc3c28e-dcae-11e6-8ce2-e65cfd5bdd5f.png">

**Comment by samreid** [comment]
Desired for https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/32

**Comment by samreid** [comment]
Here is the behavior I see:

Explore screen:
- [x] voltmeter reads values within same wire
- [x] voltmeter reads values within same vertex
- [x] voltmeter reads values from vertex to wire
- [x] voltmeter produces no reading in the middle of a battery

Therefore the explore screen behavior seems correct.

Black Box Screen:
- [x] Explore: voltmeter reads values within wire stub
- [x] Explore: voltmeter reads values within wire stub vertex
- [x] Explore: voltmeter reads values within wire stub vertex to wire body
- [x] Test: voltmeter reads values from wire stub vertex to wire body
![image](https://cloud.githubusercontent.com/assets/679486/22082062/6f91b0c8-dd83-11e6-8fa6-94ddcf39ecad.png)
- [ ] Test: voltmeter should read wire body->wire body.  This works in some parts but fails in some parts:
![image](https://cloud.githubusercontent.com/assets/679486/22082085/8c42b80c-dd83-11e6-93ca-9d66a5faf15d.png)
![image](https://cloud.githubusercontent.com/assets/679486/22082104/a555cd20-dd83-11e6-9817-dc56b1e054b4.png)

Also noted:
Voltage should not read out in an empty vertex.  Hopefully will be solved by #31 
![image](https://cloud.githubusercontent.com/assets/679486/22081993/1fba415a-dd83-11e6-976b-19ef55beec44.png)

@arouinfar so is the main (only?) problem to fix this one? "Black Box Screen: Test: voltmeter should read wire body->wire body.  This works in some parts but fails in some parts:"

**Comment by samreid** [comment]
I'm not seeing any such gaps (Black Box Screen/Test) with the ammeter.

**Comment by samreid** [comment]
The gaps were being caused by the old black box interface vertices reading through the box.  Fix forthcoming.

**Comment by samreid** [comment]
Fixed above in the branch.  In #33 we can consider moving that change to master.

**Comment by samreid** [comment]
Proposed fix is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.1/circuit-construction-kit-black-box-study_en.html

@arouinfar can you please review/test?

**Comment by arouinfar** [comment]
Looks good @samreid.

**Comment by arouinfar** [comment]
Commented on the wrong issue. Reopening.

**Comment by arouinfar** [comment]
> @arouinfar so is the main (only?) problem to fix this one? "Black Box Screen: Test: voltmeter should read wire body->wire body. This works in some parts but fails in some parts:"

Yes, I believe so. Everything looks good in 1.0.8.
