### ISSUE TITLE
Publish a prototype containing only the explore screen

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#29]
On 1/13/17 10:58 AM, Kathy Perkins wrote:
> Hi Sam, Amy, Ariel,
>
> At various points in the past month or so, I've talked with you about providing our users with an interim version of CCK for them to use and try out while we continue to work toward CCK:DC. Amy and I discussed this yesterday, and she and I agree that the first screen of the version that Shima is using seems pretty robust and useful.
>
> So what I was thinking is that we could post a version of this screen at:
> https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html
> (Here because then if someone has this link on a webpage or something it will pull up the real CCK DC once it is posted)
> And name in the Joist bar put the name: "Circuit Construction Kit Preview" or "Circuit Construction Kit Alpha" or or "Circuit Construction Kit (in progress)"(or something like that)
>
> It would not be navigable to from our homepage --- but we would disseminate it to users via email, facebook, twitter ... so to those in our network.
>
> It's the term when circuits is taught in the classroom, and its been quite a while since some users donated to our (not-fully-funded) crowdfunding campaign.
>
> Thoughts?
> Kathy

**Comment by samreid** [comment]
Amy, can you please advise on the best "stable" version to base this on?

Best Regards,
Sam

**Comment by arouinfar** [comment]
@samreid I think version 1.0.4 with the addition of the 0.5 tweaker increments would be the best candidate.

**Comment by samreid** [comment]
Marked as high priority since @kathy-phet said "4 weeks from now might not be useful to them"

**Comment by arouinfar** [comment]
@samreid the prototype should not include the modification made to the current meter in #6 to display an imprecise value when shorted.

**Comment by samreid** [comment]
I created a new repo "circuit-construction-kit-prototype" but then remembered that @kathy-phet wanted this URL to be the same place the "DC" one will eventually be.  So I think I'll delete that repo and proceed with the "circuit-construction-kit-dc" repo.  Not sure what to do for version number.  Using 1.0 now means we could not use it later when we publish the real 1.0.  Perhaps I'll publish it as 0.1?

**Comment by samreid** [comment]
I'll take dependencies.json from http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.4-phetio/dependencies.json

@zepumph and I decided on this version name: 1.0-prototype.1

**Comment by samreid** [comment]
Therefore it seems the branch should be named "1.0"

**Comment by samreid** [comment]
Sadly, SimVersion cannot parse "1.0-prototype.1".  Perhaps I'll try "1.0.0-prototype.1"

**Comment by samreid** [comment]
Published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-prototype.1/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
Oops, I must fix the name.

**Comment by samreid** [comment]
The name is fixed in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-prototype.2/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
This issue is on hold pending testing, when testing is complete, please reassign to me.

**Comment by samreid** [comment]
@pixelzoom recommends changing the version name from "-prototype" to "-dev", I agreed this is a good plan and will do it for next version, if any.

**Comment by samreid** [comment]
I'm going to move this issue to the more appropriate repo.

**Comment by samreid** [comment]
We'll track this in the above issue, closing.
