### ISSUE TITLE
Show the electrons in the wire stubs (critical)

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#30]
From https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/21

Timeline is "sometime in February"

**Comment by samreid** [comment]
Desired for https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/32

**Comment by samreid** [comment]
Fixed above, leaving open until ready for review.

**Comment by samreid** [comment]
Proposed fix is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.1/circuit-construction-kit-black-box-study_en.html

@arouinfar can you please review/test?

**Comment by arouinfar** [comment]
👍
