### ISSUE TITLE
Publish 1.0.8+ for Shima for February

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#32]
This includes the issues I'll mark below this comment.

**Comment by samreid** [comment]
The issues marked above are the currently known issues we would like fixed for Shima for February.

**Comment by samreid** [comment]
I'm considering whether to continue in the somewhat "stale-but-safe" branches or jump over to master.  Based on the following:

* not all of the changes above are trivial
* there are code improvements in master that will simplify development of this version
* we would like to be testing on master, not on stale branches

I'm inclined to jump to master.  Though if this was due Feb 1 it would be a different story than if this was due Feb 28.  Perhaps we should find out the exact timeline before deciding.

**Comment by samreid** [comment]
From #21:

> Last I heard, Shima did not have a precise starting date for the classroom study, but I've replied to ask her for a general estimate of when in February (early vs. late) they'll need a new version.

**Comment by samreid** [comment]
It looks like the cck-common branch is missing some commits (perhaps published as dev instead of production/rc?)

**Comment by samreid** [comment]
I've created proposed fixes for the top 3 issues, leaving the last issue until we know the timeline.  I'll publish a dev version for testing.

**Comment by samreid** [comment]
Published here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.1/circuit-construction-kit-black-box-study_en.html

I'll reassign individual issues to @arouinfar for testing.

**Comment by samreid** [comment]
Everything is fixed except for the tricky issue which may not be necessary anyways.   @kathy-phet and @arouinfar are going to discuss it in #31.  This issue is on hold until then.

**Comment by samreid** [comment]
The tricky issue is fixed in #31 and we are awaiting testing of another minor improvement in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/36

**Comment by arouinfar** [comment]
I'm going to tag a few more issues that should be addressed for the classroom version of CCK:BB.

**Comment by samreid** [comment]
I created a testing version at http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.9/circuit-construction-kit-black-box-study_en.html and asked @arouinfar to review #37 and #72.  If they seem good, this could be a candidate for sharing.

**Comment by samreid** [comment]
I shared a new version, closing.
