### ISSUE TITLE
For classroom study, add an option to hide the reveal button

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#37]
For the classroom study with CCK:BB, they want to hide the Reveal button so they cannot check the answer. 

Not sure if this will be a query parameter, phet-io call or something else.

**Comment by arouinfar** [comment]
Tagging for #32.

**Comment by samreid** [comment]
It is already tandemized, so perhaps this can easily be done with PhET-iO.

**Comment by samreid** [comment]
Here is the URL that launches with the 11 reveal buttons hidden:

http://localhost/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?brand=phet-io&ea&screens=2&webgl=false&phet-io.standalone=true&phet-io.expressions=[[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene1SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene2SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene3SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene4SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene5SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene6SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene7SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene8SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene9SceneView.revealButton%22,%22setVisible%22,[false]],[%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.scene10SceneView.revealButton%22,%22setVisible%22,[false]]]

**Comment by samreid** [comment]
That URL is somewhat unwieldy and indeed would change if republishing in master due to new query parameter API.  Perhaps good enough for now?  But it should be tested on the platforms to be used in the classroom to make sure it accepts large URLs.

**Comment by samreid** [comment]
I'll add this query parameter in master then backport to the branch: showRevealButton=false

**Comment by samreid** [comment]
OK it's in both branches and ready for testing in next version.

**Comment by samreid** [comment]
Published here for testing: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.8-dev.9/circuit-construction-kit-black-box-study_en.html?showRevealButton=false

@arouinfar can you take a look?

**Comment by arouinfar** [comment]
Looks good!
