### ISSUE TITLE
Rename Black Box scenes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#4]
Shima reported

> My individual concern and we had the discussion about it with Kathy as well is about the clarity of the labels for the two tabs: "Investigate Circuit" and "Build Circuit", my main concern is with the "build" label, I do not think this label convey the purpose of this tab clearly. Maybe "test circuit", or "test answer" can be better label for this tab. More radical suggestion can be to simplify the labels to: "Explore" & "Test." All said, the naive participant could understand the meaning of this label. This makes me more curios to test the label with more naive participants to be able to say which label is more clear.

**Comment by arouinfar** [comment]
It's not clear if she'd prefer Test Circuit/Test Answer or Explore/Test. I will follow up with her and report back.

**Comment by arouinfar** [comment]
Just heard back from Shima, and she prefers to use "Explore" and "Test" for the scene names.

**Comment by samreid** [comment]
Renamed in the above commit, marking as ready for testing in next version.

**Comment by arouinfar** [comment]
👍
