### ISSUE TITLE
Create new stable SHAs

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#40]
From https://github.com/phetsims/circuit-construction-kit-common/issues/72#issuecomment-277304504

Master has diverged so much from the legacy branch that it is no longer to automatically or semi-automatically merge the changes. All changes now have to be done manually, this means extra work during development and that everything must be tested twice (in the branch and in master).  The best long term plan is to abandon the legacy branch and create a new stable branch from master--this would require one-time exhaustive testing but would save us the most time in the long run.  Every time we say "what if there is just one more minor change for the stale branch" there are many more changes for the stale branch.  So we should plan to stop making changes to this branch soon, whether (a) it requires no more changes or (b) we can use a fresh branch from master.

When we do this will be up to @arouinfar @kathy-phet and @ariel-phet.

**Comment by samreid** [comment]
One point to refine this, some semi-automatic backports are possible for common feature (i.e. not specific to black box).  For instance, I was able to cherry pick some of the fire.

**Comment by ariel-phet** [comment]
@samreid in terms of the QA queue next week would probably be a good time, once Make-a-Ten is published, we will likely have a bit of a lull in high priority items for possibly a week or so (especially since the app is now republished, and some recent a11y iO sims are out the door). 

So I would say sooner than later, and this task would come above testing a CCK prototype IMO

**Comment by samreid** [comment]
If master makes it through QA, it would also be a suitable prototype.

**Comment by arouinfar** [comment]
@samreid I'll defer to @ariel-phet on this issue. My only concern is that we will be able to make the late Feb/early March deadline for Shima's studies.

**Comment by ariel-phet** [comment]
@samreid lets go ahead with creating this task as we have some current space in QA that will soon close up in a week or two

**Comment by samreid** [comment]
@arouinfar can I include the labels checkbox and component labels like this:

![image](https://cloud.githubusercontent.com/assets/679486/22679245/d78dc2fe-ecbd-11e6-9c95-149f7b2e67b6.png)

For Shima, or should I strip it out before doing a build?

**Comment by arouinfar** [comment]
@samreid I honestly don't know. My best guess would be that you should strip the labels before doing a build for Shima, but I will email her to confirm.

**Comment by samreid** [comment]
Sounds good, I don't want to miss our testing window, so if you don't hear from her by noon tomorrow or so I'll probably do a build anyways.  If we have to strip the labels from the support branch, or add an option to have them off by default it will be OK.

**Comment by arouinfar** [comment]
@samreid thanks for the update. I'll let you know as soon as I hear back.

**Comment by arouinfar** [comment]
@samreid the Labels checkbox (default on) can be included in the version of CCK:BB that you build for Shima.

Shima replied:
> Having label for elements in both CCK & CCK-BB are more positive than negative feature. So I am totally fine in having them in CCK-BB tab as well.

When following up about the default state of the Labels checkbox, she said:
>default can be on, and then I will switch it off if need be

**Comment by arouinfar** [comment]
@samreid I saw CCK:BB on master, and I wanted to give you a heads up that the lifelike/schematic option should not be in what is published for Shima.

**Comment by samreid** [comment]
Agreed, I'll suppress that before publishing tomorrow.

**Comment by arouinfar** [comment]
Excellent, thanks!

**Comment by samreid** [comment]
I commented out the lifelike/schematic buttons for now.

**Comment by samreid** [comment]
I'll create a 1.1-phetio branch for this.  In case significant problems arise, we would still be able to use the 1.0 legacy branch.

**Comment by samreid** [comment]
RC1 was published here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.1/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

With wrappers here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.1/wrappers/index/

I'll create a test task.

**Comment by samreid** [comment]
After a few RC's the new SHAs are looking much more solid than old shas, thanks @phet-steele and @arouinfar, closing.
