### ISSUE TITLE
Add 5 additional black boxes 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#41]
Shima has requested that we add four additional black boxes to the version she will use for the Stanford post-test on March 10 and 11. These black boxes won't be necessary for the classroom study, though I don't imagine they'll do any harm if they are included there too.

@samreid is it relatively straight forward to add additional black boxes? I've asked Shima to send me screenshots as soon as she has them ready.

**Comment by samreid** [comment]
I would love to do #40 before implementing something like this.  Can you please comment on #40?

**Comment by arouinfar** [comment]
@samreid  here are the additional black boxes that Shima has requested.

Black Box 11:
> 40 ohm top to bottom + 10 ohm left to right
<img width="302" alt="bb-1" src="https://cloud.githubusercontent.com/assets/8419308/22759913/6e8b5960-ee11-11e6-899f-e40a4710fe5a.png">

Black Box 12:
> 40 ohm left to right + 40 ohm right to top + wire top to bottom + wire bottom to left
<img width="300" alt="bb-2" src="https://cloud.githubusercontent.com/assets/8419308/22759921/74051926-ee11-11e6-8e77-6b3b8627478d.png">

Black Box 13:
> 40 ohm + 10 volt bottom to left + 40 ohm bottom to top
<img width="303" alt="bb-3" src="https://cloud.githubusercontent.com/assets/8419308/22759924/78097350-ee11-11e6-9c9b-0b53e3c6e8ec.png">

Black Box 14:
> 10 volt bottom to left + 40 ohm bottom to top
<img width="295" alt="bb-4" src="https://cloud.githubusercontent.com/assets/8419308/22759926/7c52413a-ee11-11e6-95b5-e209d16d4909.png">

Black Box 15:
> wire top to bottom + wire left to right + 40 ohm bottom to left
<img width="290" alt="bb-5" src="https://cloud.githubusercontent.com/assets/8419308/22759935/7f934114-ee11-11e6-808c-963a3e03e985.png">

**Comment by samreid** [comment]
Note to self: implement these as a single commit so it is easy to cherry pick.

**Comment by samreid** [comment]
Roughly, my procedure:

1. Change black box scene model to read:

```js
    // Keep track of what the user has built inside the black box so it may be restored.
    var userBlackBoxCircuit = new CircuitStruct( [], [], [], [], [], [] );

    setInterval( function() {
      console.log( JSON.stringify(self.circuit.toStateObject(),null,2) );
    }, 2000 );
    var circuit = this.circuit;


    var addWireStubs = function() {
      return;
      // Add wire stubs outside the black box, see https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/21
      for ( i = 0; i < trueBlackBoxCircuit.vertices.length; i++ ) {
```

2) Change BlackBoxScreenModel.js to start with 'scene9'

3) create the black box. Copy paste into the ChallengeSet.  Delete resistance, replace 0.0001 with resistivity, delete options.  For vertices missing options, add options with attachable false.

**Comment by samreid** [comment]
I visually reviewed the changes but only tried wiring up a few of them.  Would be good for @arouinfar to test thoroughly after I post the next version.

**Comment by samreid** [comment]
@arouinfar this version contains the new 5 black boxes, can you please test them?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.5/wrappers/index/

**Comment by phet-steele** [comment]
Challenge 11 is mostly fine, there's a slight protrusion of the resistor on the leftmost vertex:
<img width="573" alt="screen shot 2017-02-17 at 10 32 37 am" src="https://cloud.githubusercontent.com/assets/5863899/23076205/a900dcea-f4fc-11e6-97fe-2286ae5af727.png">

Challenge 12 has the same small issue as 11, but also a label that pokes through the top:
<img width="675" alt="screen shot 2017-02-17 at 10 35 04 am" src="https://cloud.githubusercontent.com/assets/5863899/23076244/d29d3f4e-f4fc-11e6-9a3d-ac5da7a7a91b.png">

Challenge 13 has the same issue as 11, but also doesn't have solder on the rightmost vertex. This sort of gives away part of the answer, but maybe it's fine?
<img width="659" alt="screen shot 2017-02-17 at 10 36 04 am" src="https://cloud.githubusercontent.com/assets/5863899/23076283/03b19350-f4fd-11e6-8eb0-519d950f92e0.png">

Challenge 14 doesn't have solder like 13, and also has a very obvious battery poking through:
<img width="703" alt="screen shot 2017-02-17 at 10 37 15 am" src="https://cloud.githubusercontent.com/assets/5863899/23076320/25ff6f7c-f4fd-11e6-9ae0-ba5c7eac2057.png">

Challenge 15 has components poking through the left and bottom:
<img width="663" alt="screen shot 2017-02-17 at 10 38 38 am" src="https://cloud.githubusercontent.com/assets/5863899/23076351/4d2bf05c-f4fd-11e6-9bcc-6401de143075.png">

**Comment by samreid** [comment]
Thanks @phet-steele, I'll try again.

**Comment by arouinfar** [comment]
Thanks for your careful review @phet-steele. 

> Challenge 13 has the same issue as 11, but also doesn't have solder on the rightmost vertex. This sort of gives away part of the answer, but maybe it's fine?

I think the missing solder in black boxes 13 and 14 is a bit problematic. Perhaps we can attach a short wire stub to the inside of the black box to create the the solder joint at the edge of the box?

**Comment by samreid** [comment]
I'm planning on adding internal struts on all of the vertices.  It will make the topology look more complicated but it will behave the same.  For instance, Black Box 12 will be:
![image](https://cloud.githubusercontent.com/assets/679486/23076962/c5b68e86-f4ff-11e6-94b3-b2fd671fbf34.png)

@arouinfar is that OK?

**Comment by arouinfar** [comment]
I think the internal struts will be fine @samreid, though for Black Box 12, those should be 40 ohm resistors. :)

**Comment by samreid** [comment]
Got it, thanks!

**Comment by samreid** [comment]
@arouinfar are these resistor bands correct?

![image](https://cloud.githubusercontent.com/assets/679486/23077461/daee6b32-f501-11e6-8712-0dc54c7d41f7.png)

**Comment by arouinfar** [comment]
@samreid the picture shows a 25 ohm resistor connecting the left and right terminals, but the text specified 10 ohms. I'm not sure which Shima prefers. I'll follow up with her now.

**Comment by samreid** [comment]
Thanks @arouinfar.  I published RC6 with fixes for the problems @phet-steele found, and I'm using the 10 Ohms from the text.  Changing values are easy, please test and let me know.

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.6/wrappers/index/

**Comment by arouinfar** [comment]
Thanks @samreid. I'll let you know as soon as I hear back from Shima.

**Comment by arouinfar** [comment]
The black boxes in rc.6 are functionally the same as those initially provided in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/41#issuecomment-278480010. I'll leave this self-assigned until I receive confirmation of the desired resistance in Black Box 11.

**Comment by arouinfar** [comment]
The internal struts have also fixed all instances of black box components peeking through.

**Comment by arouinfar** [comment]
Shima replied:

> Amy, either way is fine. But, I would vote for 25 ohm, to make their calculation harder.

@samreid can you update the 10 ohm resistor in Black Box 11 to 25 ohms?

**Comment by samreid** [comment]
Brace yourself for RC.7

**Comment by samreid** [comment]
RC.7 is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.7/wrappers/index/

@arouinfar can you please see if there's anything else to do before promoting this to a production release and sharing it with Shima?

**Comment by arouinfar** [comment]
@samreid rc.7 has been running smoothly for me, and I haven't run into any further issues. Please go ahead and publish the production version.

**Comment by samreid** [comment]
@arouinfar I created a production version here:
https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.1.0-phetio/wrappers/index/

I also changed an internal variable name in the black box screen, if you could spend a few minutes spot testing it on one platform it would be great.  After that, can you please share the link to our contacts?  As you did before, please include the various links with query parameters.

**Comment by samreid** [comment]
> These black boxes won't be necessary for the classroom study, though I don't imagine they'll do any harm if they are included there too.

It may be good to double-check that point, or at least make sure they are aware of it and would hence alert us if there is a problem.

**Comment by arouinfar** [comment]
@samreid the link you provided in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/41#issuecomment-280757880 looks like it's only good for testing. Have you created a version for data collection? I previously sent Shima a link that looked something like this:

https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.0.4-phetio/wrappers/login/login.html?wrapper=record&sim=circuit-construction-kit-black-box-study&metacog&publisher_id=29da48a1&application_id=1f6fc35021bb7d398308c73123802036&widget_id=record-circuit-construction-kit-black-box-study&validationRule=crossCheckID&validationPrefix=cck16

**Comment by arouinfar** [comment]
@samreid it would also be helpful to know what ID's they should use with the data collection version. I previously instructed them to:

> For testing purposes, please use cck16999k as the ID.  When you’re ready to use it with students, the ID’s should be of the form:
cck16001a
cck16002b
...
cck16026z
cck16027a
cck16028b
etc.

Is this still correct?

**Comment by samreid** [comment]
@zepumph confirmed this will be the first time we are using learner_token with a 3rd party.  @zepumph and I tried logging some sample data in https://github.com/phetsims/phet-io/issues/1048 and will report back after it is complete.  If that works, we will be able to share that URL to Engin.

**Comment by samreid** [comment]
The data collection and playback seemed to work well, but with the same widget_id, I was receiving 4.7GB of data.  Hence I've changed the widget-id so these results don't combine with the previous results.  @arouinfar please request Engin to perform a test with this link (1-2 minutes of recording), then to let us know when it's done and we can make sure he can access the data OK.

https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.1.0-phetio/wrappers/login/login.html?wrapper=record&
metacog&publisher_id=29da48a1&key_name=stanford_record_circuit-construction-kit-black-box-study&
widget_id=record-circuit-construction-kit-black-box-study-1.1&validationRule=crossCheckID&validationPrefix=cck16

**Comment by arouinfar** [comment]
The latest version has been delivered to Stanford, so I think we can go ahead and close this issue. We can track data recording issues in https://github.com/phetsims/phet-io/issues/1048.
