### ISSUE TITLE
Wire stubs easily editable after switching to and from Test --> Explore

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-black-box-study#43]
1. Click Test
2. Click Explore

Wire stubs can be moved no differently than another wire. Happens on any BB selection:

![cckbbio01](https://cloud.githubusercontent.com/assets/5863899/22760991/207e0718-ee16-11e6-94c7-4157c74fb6cf.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by phet-steele** [comment]
Instead of cutting, if you *try* to pull a wire stub around by its vertex (one of the red vertices), then manipulate the stub another way, you kill the sim and get a handful of errors:

https://drive.google.com/file/d/0B3HJopSo_QqLNHZGV1BOZ002Tm8/view?usp=sharing

<img width="535" alt="screen shot 2017-02-08 at 4 36 47 pm" src="https://cloud.githubusercontent.com/assets/5863899/22762803/67c8f756-ee1e-11e6-9e2a-68284db19696.png">

Commenting here because, so far, it seems inextricably tied to being able to interact with the wire stubs.

**Comment by samreid** [comment]
I used this test code:

```js
      circuit.vertices.forEach( function( v ) {
        console.log( 'vertex ' + v.index + ', black box interface: ' + v.blackBoxInterfaceProperty.get() );
      } );
      circuit.circuitElements.forEach( function( c ) {
        console.log( 'circuit element ' + c.constructor.name + ' (' + c.startVertexProperty.value.index + '->' + c.endVertexProperty.value.index + '), interactive: ' + c.interactiveProperty.get() );
      } );
```

with these query parameters `vertexDisplay=index&dev` and revealed that when switching to explore, the wire stubs were being set to be interactive, which enabled the cut button.  Skipping this step for wire stubs seems to solve this problem.

**Comment by samreid** [comment]
Fixed in the above commits, leaving open for verification in RC.2.

**Comment by samreid** [comment]
Ready for verification in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

**Comment by phet-steele** [comment]
Looks fixed to me! https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/43#issuecomment-278501506 was a pretty dire consequence, I'll keep an eye out for it.
