### ISSUE TITLE
Fire is offset from shorted elements in a BB

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-black-box-study#44]
1. Short a circuit element while "Test" - ing (make it burst into flames).
2. Switch to another editing state (Explore or Reveal)
3. Switch back to "Test".

The fire images will be close to the corner of the screen. Manipulating the circuit elements on fire will reposition the flames:

![cckbbio03](https://cloud.githubusercontent.com/assets/5863899/22761742/546970e6-ee19-11e6-920d-b78b5c8c2dbb.gif)

The same bug exhibits itself with hidden circuit elements:
(There's a battery inside of this challenge)

![cckbbio04](https://cloud.githubusercontent.com/assets/5863899/22761834/bd695426-ee19-11e6-8687-86acd57f7fb9.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by samreid** [comment]
Fixed in the preceding commit and ready for testing in the next rc.

**Comment by samreid** [comment]
Ready for verification in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

**Comment by phet-steele** [comment]
Fixed in rc.2 indeed!
