### ISSUE TITLE
Query Parameter to hide "Show Electrons" checkbox no longer works

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#45]
For https://github.com/phetsims/tasks/issues/781.

The query parameter previously used to hide the "Show Electrons" checkbox no longer works. My suspicion is that the addition of the "Labels" checkbox to the panel may be to blame.

Here's the query parameter in question:

?phet-io.expressions=%5B%5B%22circuitConstructionKitBlackBoxStudy.exploreScreen.view.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D,%5B%22circuitConstructionKitBlackBoxStudy.blackBoxScreen.view.warmupSceneView.displayOptionsPanel%22,%22setVisible%22,%5Bfalse%5D%5D%5D

**Comment by samreid** [comment]
In the above commit, I added 2 query parameters.

`showElectronsCheckBox=false` will hide the electrons checkbox, while leaving the "labels" checkbox

`showControlPanel=false` will hide the entire panel (with both labels and electrons, and eventually more controls to come in the dc version).

Leaving open for verification when rc.2 is ready.

**Comment by samreid** [comment]
Ready for verification in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone&showElectronsCheckBox=false

and 

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone&showControlPanel=false

**Comment by phet-steele** [comment]
@samreid they work for me, nice work! I'll assign to @arouinfar to check out so she is aware.

**Comment by arouinfar** [comment]
@samreid looks great, thanks! These new query parameters are much easier to remember too. :)
