### ISSUE TITLE
State is no longer saved when switching between BB challenges

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-black-box-study#46]
It is my understanding that state is supposed to be saved.

I have a bunch of objects out in the warm-up, then switch away and back to it and the objects are reset:

![cckbbio06](https://cloud.githubusercontent.com/assets/5863899/22798320/b1c31440-eebe-11e6-8833-686a8096a729.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks#781.

**Comment by samreid** [comment]
The workaround for https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/36 introduced this problem.

**Comment by samreid** [comment]
The transparency effect is because the wire is transparent and the solder is behind the wire.

**Comment by samreid** [comment]
Fixed in the above commit, leaving open until verified in RC.3.

**Comment by arouinfar** [comment]
When this issue is verified, we should also make sure that the Reset All button only effects the current black box. Given that the states weren't properly saved in rc.2, it was impossible to test the Reset All behavior.

**Comment by phet-steele** [comment]
Looks good in rc.3.

> we should also make sure that the Reset All button only effects the current black box.

It does!
