### ISSUE TITLE
Components are being layered under the BB when switching between challenges

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-black-box-study#48]
@samreid, in rc.3 anything attached to the BB will be layered above the BB at first, but then be layered under it when switching to and back from another challenge.

Before switch:
<img width="675" alt="screen shot 2017-02-15 at 11 53 28 am" src="https://cloud.githubusercontent.com/assets/5863899/22990171/8c01c4c0-f375-11e6-8736-2900724fdd93.png">

After switch:
<img width="646" alt="screen shot 2017-02-15 at 11 53 37 am" src="https://cloud.githubusercontent.com/assets/5863899/22990182/9520e2ca-f375-11e6-8059-55fd0d8a3c88.png">

Clicking on solder joints will return their respective circuit elements to be above the BB (resistor vertex clicked here, only):
<img width="764" alt="screen shot 2017-02-15 at 12 00 02 pm" src="https://cloud.githubusercontent.com/assets/5863899/22990405/518a0aae-f376-11e6-8ea0-f1bab039a2cb.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/781.

**Comment by samreid** [comment]
Fixed above (except the solder next to the black box is somehow getting in front).  I'll mark this issue as fixed pending testing.

**Comment by samreid** [comment]
Ready for testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.4/wrappers/index/

**Comment by phet-steele** [comment]
This particular issue is fixed in rc.4, thanks @samreid!

> Fixed above (except the solder next to the black box is somehow getting in front).

I believe that's being tracked in another issue, so closing.
