### ISSUE TITLE
Reveal triggers pause

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#49]
Found by @phet-steele during https://github.com/phetsims/tasks/issues/781.

In Test mode, pressing Reveal will trigger a paused state.

Consider this example
* Start in Explore in Play mode.
* Switch to Test. Pause is triggered. (Desired behavior.)
* Press play, and then Reveal.
* Reveal kicks the sim back into Pause mode.
![playpausereveal](https://cloud.githubusercontent.com/assets/8419308/22994222/5aa84a30-f383-11e6-8f30-7a08ffd13205.gif)

I have the feeling this occurs because the Reveal button temporarily switches to Explore (and switching between scenes will trigger the pause button). However, I think triggering a pause on Reveal can be problematic. Essentially, students will only be able to compare their circuit to the black box contents while in a paused state. 

Ideally, if the Reveal button is pressed while in Play mode, the black box contents would also be shown in Play mode. Triggering a pause in this situation may cause confusion.

**Comment by samreid** [comment]
The explanation is that the circuit pauses when it changes, and "reveal" changes the circuit.  I'll need to add separate logic to address this case.

**Comment by samreid** [comment]
It is also pausing when switching between explore and test, probably for the same reason.  @arouinfar please correct me if I'm wrong but that doesn't seem desirable either.

**Comment by samreid** [comment]
It is easy enough to keep the circuit running when pressing "reveal" but the same strategy won't work for releasing the "reveal" button or changing modes.

@arouinfar is this critical for Stanford's February usage?

**Comment by samreid** [comment]
Fixed in the preceding commits, ready for review in next rc.

**Comment by samreid** [comment]
Ready for testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.0-phetiorc.4/wrappers/index/

**Comment by arouinfar** [comment]
Looks great @samreid! The behavior feels much more natural now.
