### ISSUE TITLE
Cannot disconnect light bulb from black box terminal

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#5]
Shima reported

> When we connected a light bulb directly to a CCK-BB terminal, there was no way to disconnect it, Neither the scissors, nor the trash option showed when we clicked on the connection. This issue came up whenever the light bulb was connected to the CCK-BB directly. Each time, we had to restart the simulation to get rid of the connection. This issue did not come up when a resistor or a battery connected to the CCK-BB

I also experienced this issue in dev.23. When clicking on the center of node, the light bulb is selected, rather than the node.  I think the problem is that the click area for light bulb is something like this, which cuts quite a bit into the side node.
![image](https://cloud.githubusercontent.com/assets/8419308/18642958/1be2a9be-7e60-11e6-9681-0dd83b622208.png)

@samreid can you adjust the click areas, to be something more like this?
![image](https://cloud.githubusercontent.com/assets/8419308/18642991/4ce6d2f6-7e60-11e6-80bd-8e916d70e691.png)

**Comment by samreid** [comment]
Mouse and touch area set to the T shape described above:

![image](https://cloud.githubusercontent.com/assets/679486/20110181/8d5b3eaa-a5a0-11e6-9c62-885ee11abd1c.png)

Ready for review in next version.

**Comment by arouinfar** [comment]
Something's not right here @samreid.
![light_bulb](https://cloud.githubusercontent.com/assets/8419308/20127189/9d48abb4-a5f9-11e6-858e-e54af9af8646.gif)

**Comment by samreid** [comment]
The preceding comment seems to be unrelated to the touch areas, I'll move it to a separate issue.

**Comment by arouinfar** [comment]
The click area seems fine, otherwise. Closing.
