### ISSUE TITLE
Add new black box 16

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-black-box-study#52]
Shima said:

Dear Amy and Sam,

Can we ask to have another cck-bb activity to be added to the activity deck.
It is a three-terminal activity with one 10.00 v battery connecting top and left (the screenshot of the activity is attached).

Thanks so much,
Shima

![image](https://cloud.githubusercontent.com/assets/679486/23635478/5640e628-028d-11e7-91dd-d58f7696d18b.png)

A reminder to add adapter circuits so the battery doesn't show outside of the box.

**Comment by samreid** [comment]
Argenta said:

Yes, that's soon enough. Sorry we didn't give you a time frame initially!

We'd like to use this new box the second time we have students use the activity, as a variation on boxes 1 and 3, which they'll seen the fist time. We can use the current set of black boxes for their first use. We'll be doing a black box activity for the first time on Friday March 10, then the second time 1-2 weeks later (haven't discussed exact timing for the second black box day yet with the teachers). So I think even by end of day March 16 would be soon enough.

Thanks!
Argenta

**Comment by samreid** [comment]
> by end of day March 16 would be soon enough.

I'd better get started on this.

**Comment by samreid** [comment]
Added in the maintenance branch in the above commit and it looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/23966481/1dd8e272-0981-11e7-9b4e-af4a87bc83fd.png)

**Comment by samreid** [comment]
I think my battery is backwards.

**Comment by samreid** [comment]
After swapping vertices:

![image](https://cloud.githubusercontent.com/assets/679486/23966533/5113551e-0981-11e7-978b-421325854514.png)

**Comment by samreid** [comment]
New version published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.2-phetio/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone

@arouinfar would you like to take a look before we share it to Argenta?

**Comment by arouinfar** [comment]
Looks good @samreid.

**Comment by samreid** [comment]
I emailed:

> Hello,

> We've published a new version with the three terminal activity as "Black Box 16".  To use it, please replace the version number with "1.1.2-phetio" in your links.  Please test it out and report back about whether it is working properly.

> Best Regards,
Sam

**Comment by arouinfar** [comment]
Thanks @samreid!

**Comment by samreid** [comment]
On hold until verified with Argenta.

**Comment by samreid** [comment]
Argenta pointed out the directory was still password protected, I removed the password protection, updated partners.md and replied.  Closing.
