### ISSUE TITLE
No 1.1 branch

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/circuit-construction-kit-black-box-study#53]
There's a production version ('phet' brand) available at http://phet.colorado.edu/sims/html/circuit-construction-kit-black-box-study/1.1.2/circuit-construction-kit-black-box-study_en.html, and it's in on the website. Thus customarily, there should be an equivalent maintenance-release branch.

1.1 doesn't exist (there's a phet-io branch however??)

Will need to manually maintenance release as part of https://github.com/phetsims/special-ops/issues/68.

Assigning to @samreid to consult how to build this sim if there is no usual branch.

**Comment by samreid** [comment]
I think it was an accidental "deployed without --brand=phet-io" and we decided it was harmless since it wasn't visible on the website.  Black Box Study (phet brand) isn't meant to be on the website, perhaps we should delete it?

**Comment by jonathanolson** [comment]
@samreid, would this ever be deployed on the main website, or tracked with Yotta statistics? Deleting and then re-adding later will require special handling in Yotta (as it would have two simulation IDs for the same simulation).

@mattpen, if we decide to, what would be the order that things need to be removed in, and is it safe to remove a simulation? Would we delete it on the DB side first, then remove the files? Has this been done to your knowledge?

**Comment by samreid** [comment]
I don't recall if @kathy-phet wants to track Stanford's usage for their data-driven study or not, I have a vague recollection that she said the numbers may be too small to worry about.  When published on our website in the next few years, it will likely not have the "study" suffix.

**Comment by kathy-phet** [comment]
This version can be removed from the production server as far as I am concerned. And no statistics are needed to be collected on this version - as Sam said it is small usage. 

When we deploy a public version of Black Box, it will not have "study" in the name, so I think within Yotta we will not get confused. It would likely have a name like circuit-construction-kit-black-box, or circuit-construction-kit-game or something.

**Comment by jonathanolson** [comment]
Removed the CCK black box files from the phet.colorado.edu website. Some foreign key constraint issues removing from the DB, assigning @mattpen for that.

**Comment by mattpen** [comment]
The database entries for CCK Black Box Study have all been removed.

**Comment by mattpen** [comment]
@jonathanolson - Is it ok to close this issue now?

**Comment by jonathanolson** [comment]
Yup, thanks!
