### ISSUE TITLE
Publish new version for Stanford

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#64]
Shima is preparing to start a new round of data collection and wrote to me asking 
> I am starting another round of data collection and this time it is more in the experimental lab setting. I would need a CCK-BB version that have all the 15 activities as well as the explore/test option in the black box tab. Which version of CCK-BB should I use to make sure we are also collecting the back end data properly?
Right now for the prototyping I am using this version:
https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.1.0-phetio/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone&phetioLog=lines
However this is the one without the backend data collection, can you remind what is the equivalent version of this one though with the backend data collection feature.

Looking at [partners.md](https://github.com/phetsims/phet-io/blob/master/doc/partners.md), the latest version we delivered to her is 1.1.2. I do not know Shima's timeline, but I have followed up with her to find out.

Due to some changes with metacog storage, 1.1.2 should not be used for backend data collection again. 

In a Zoom chat @zepumph said he would publish a new version and test on metacog.

**Comment by zepumph** [comment]
I will need to test the dev library Marcus sent over in https://github.com/phetsims/phet-io/issues/1245 before updating this link. I will pump that priority and put this on hold.

**Comment by arouinfar** [comment]
Sounds good @zepumph. I will let you know the timeline as soon as I hear back from Stanford.

**Comment by arouinfar** [comment]
@zepumph heard back from Stanford, and they would like to start data collection November 20. Is this a reasonable timeline?

**Comment by zepumph** [comment]
Yes I think that this will be enough time. I'll reach out to Marcus about publishing this dev link soon. Then I will spend next week making sure that that the specific links needed are working as expected.

**Comment by zepumph** [comment]
I sent out a few bugs to Metacog and hope to hear back from them early next week. I have also been reaching out to Shima to make sure that we are all on the same page about the expectations of the study to come.

**Comment by zepumph** [comment]
We are ready to use https://cdn.metacog.com/metacog-3.4.11.min.js in the next maintenance release of CCK BBS for Shima.

**Comment by zepumph** [comment]
Testing from master:
http://localhost/phet-io/wrappers/login/login.html?sim=circuit-construction-kit-black-box-study&phetioValidateTandems=false&publisher_id=5d4c8ae1&key_name=key1&wrapper=record&validationRule=validateDigits&numberOfDigits=8&metacog&widget_id=CCK-BBS-test

**Comment by zepumph** [comment]
Testing from rc deploy:
https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.1.3-phetiorc.1/wrappers/login/login.html?wrapper=record&metacog&publisher_id=29da48a1&key_name=stanford_record_circuit-construction-kit-black-box-study&widget_id=record-circuit-construction-kit-black-box-study-1.1-test&relativeSimPath&validationRule=crossCheckID&validationPrefix=cck16

My plan is to send the above link to Shima tonight, and then we can work on testing for the next few days.

**Comment by zepumph** [comment]
I ended up publishing the version on the production server, and made it public. This way we don't have to deal with passwords. Here is my email to Shima. I'll update partners.md

```
Shima,

Hello again, I have a link ready for testing as you get ready for your study on Monday. I apologize that it has taken so long to get back to you. We have been working with Metacog intimately this week. 

The link below will take you a login page just like last time. I set it up to be identical in process to last time. I didn't know if we wanted to update anything, like a different set of ids, or saving to a different place so that we don't mix previous logs with these ones (you can always sort sessions by time when retrieving data, but sometimes it's nice for them to be searchable with different widget_ids). 

Basically I want to make sure of a few things:
* Are ids starting with cck16 alright with you? There is still the letter/number combo afterwards like "1a" and "2b"
* I want to make sure that you realized this is only a testing link. Notice in the link below the widget_id of this contains 'test'. The goal is to hammer out any of the problems now instead of next week.
* The link is public, so anyone with this link will record to Metacog. You shouldn't need to enter a password or anything to use it.
* In this new version, there is a message that will appear each time you try to back/exit out of the recording simulation page. This is very important. Make sure that each time you click STAY. This way the extra events that have built up during the recording session can drain out of the queue and be sent to the server. As soon as the progress bar reaches 100%, all events will have sent, and you can quit from the page. This will also be very important to communicate to participants during the study.

https://phet-io.colorado.edu/sims/circuit-construction-kit-black-box-study/1.1.3-phetio/wrappers/login/login.html?wrapper=record&metacog&publisher_id=29da48a1&key_name=stanford_record_circuit-construction-kit-black-box-study&widget_id=record-circuit-construction-kit-black-box-study-1.1-test&validationRule=crossCheckID&validationPrefix=cck16

Let me know what else I can do for you. I look forward to hearing how things go.

Thanks,
Michael

**Comment by zepumph** [comment]
Next I need to make up a few questions to send her to ask about browser and computer.

**Comment by zepumph** [comment]
I sent those off too. From here I will support her as she needs. Reducing priority.

**Comment by zepumph** [comment]
Closing this. We will create new issues as needed.
