### ISSUE TITLE
Change color of reveal button on hold

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#7]
Shima reported

> When pressing the reveal button, maybe it would be helpful to change the color of the button when it is pressed down, and when it is released have the color change back to the initial color.

I like this suggestion @samreid, though I don't have any particular color preference. Maybe a green would look nice?

**Comment by samreid** [comment]
I went with a light green and it seemed OK.

**Comment by arouinfar** [comment]
Looks good!
