### ISSUE TITLE
Show values during Reveal

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#8]
Shima Reported:

> Also, as users cannot interact with the revealed solution, it is helpful to show the value of the resistors and batteries, otherwise it is hard to find the quantitative answer.

This sounds like a very helpful feature. @samreid can you display the values (resistances of resistors and battery voltage) upon reveal?

**Comment by samreid** [comment]
This would likely take > 10 times as long to implement as any of the other features I have worked on so far.  I'll save it for later.

**Comment by samreid** [comment]
It may be simplest (regarding bounds and layout) if we can overlay the values on the components, with a white background and black text (so the text is sure to show).  If we show the values away from the components it could be overlapped by something else, and may throw off the display bounds.

@arouinfar does that sound reasonable to you?

**Comment by arouinfar** [comment]
> we can overlay the values on the components, with a white background and black text (so the text is sure to show)
Sounds reasonable to me @samreid!

**Comment by samreid** [comment]
If the values rotate with the components, then they could be sideways or upside down.

**Comment by arouinfar** [comment]
I think that would still be acceptable @samreid. At most, students are reading 4 values when revealing the contents of the black.

**Comment by samreid** [comment]
The values are somewhat hard to read because they are already behind a layer of transparency.

**Comment by samreid** [comment]
Fixed in the above 2 commits.

**Comment by arouinfar** [comment]
Looks great @samreid!
