### ISSUE TITLE
Prevent elements overlapping black box boundary when "snapping"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-black-box-study#9]
Shima reported:

> We talked about the snap to CCK-BB feature in the "build" tab, however couple of times the wire snapped to the exact borders of CCK-BB and cover part of the border line of CCK-BB. This can be quite confusing, I think the snap feature should be limited to within border instead of within and on the borders of CCK-BB.

@samreid is it possible to slightly push elements away from boundary of the black box when snapping? For example a wire released above or below the black box, could snap into the black box like this, rather than overlapping the top/bottom border of the box.
![image](https://cloud.githubusercontent.com/assets/8419308/18643432/48162f22-7e62-11e6-9718-108865851124.png)

**Comment by samreid** [comment]
Fixed above.  This will require some testing in case other features were depending on the boundary being right at the edge of the box.

@arouinfar will you have time to test this today, if I publish a version around 4pm or so?

**Comment by arouinfar** [comment]
I will indeed @samreid.

**Comment by arouinfar** [comment]
This seems to be working so far @samreid. However, I want test a bit more thoroughly tomorrow morning.

**Comment by arouinfar** [comment]
Still looks good! Closing.
